version: "3.8"
services:
  api:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - ".:/app"
    depends_on:
      - db
    
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_DB=db"
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: