# Generated by Django 4.0.5 on 2022-06-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleToClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.FloatField(blank=True)),
                ('hours', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.currencies')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('birth_date', models.DateField(blank=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('birth_country', models.CharField(blank=True, default='', max_length=100)),
                ('birth_city_or_village', models.CharField(blank=True, default='', max_length=100)),
                ('is_current_student', models.BooleanField(blank=True, default=False)),
                ('left_at', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.schoolclasses')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='uploads/')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('username', models.CharField(blank=True, default='', max_length=50)),
                ('password', models.CharField(blank=True, default='', max_length=16)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='uploads/')),
                ('sex', models.CharField(blank=True, default='', max_length=10)),
                ('birth_date', models.DateField(blank=True)),
                ('is_teacher', models.BooleanField(blank=True, default=False)),
                ('is_secretary', models.BooleanField(blank=True, default=False)),
                ('is_accounting', models.BooleanField(blank=True, default=False)),
                ('is_driver', models.BooleanField(blank=True, default=False)),
                ('is_parent', models.BooleanField(blank=True, default=False)),
                ('is_cashier', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('street', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClassModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.moduletoclass')),
                ('teach_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.teacherclass')),
            ],
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='teach_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user'),
        ),
        migrations.CreateModel(
            name='StudentsAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('street', models.CharField(blank=True, default='', max_length=100)),
                ('building', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.students')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user'),
        ),
        migrations.CreateModel(
            name='StudentRelative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_fullname', models.CharField(blank=True, default='', max_length=100)),
                ('mother_fullname', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.students')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('amount_paid', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.currencies')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.feetype')),
                ('payment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.paymentcategories')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.students')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarksEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_score', models.FloatField(blank=True)),
                ('student_grade', models.FloatField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.moduletoclass')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.students')),
                ('teach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.BooleanField(blank=True, default=False)),
                ('studding_range_year', models.CharField(blank=True, default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.students')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBusSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.students')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBusAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_student', models.BooleanField(default=False)),
                ('arrive_school', models.BooleanField(default=False)),
                ('picked_at', models.DateTimeField()),
                ('arrived_at', models.DateTimeField()),
                ('student_subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.studentbussubscription')),
            ],
        ),
        migrations.AddField(
            model_name='paymentcategories',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user'),
        ),
        migrations.AddField(
            model_name='moduletoclass',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.schoolclasses'),
        ),
        migrations.AddField(
            model_name='moduletoclass',
            name='module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.modules'),
        ),
        migrations.AddField(
            model_name='moduletoclass',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user'),
        ),
        migrations.AddField(
            model_name='modules',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user'),
        ),
        migrations.CreateModel(
            name='EmployeePaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default='')),
                ('month', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('payment_type', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.currencies')),
                ('teach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default='')),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.currencies')),
                ('teach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='CashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('debit', models.FloatField(default=0)),
                ('credits', models.FloatField(default=0)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngouzo_api.user')),
            ],
        ),
    ]
