# Generated by Django 4.0.5 on 2022-06-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngouzo_api', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
